import type { TokensMap } from './types'

export const sampleTokens: TokensMap = {
  // Color Tokens
  'color.primary.base': {
    value: '#2563eb',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: ['color.primary.hover', 'color.primary.active'],
    referencedBy: ['button.background', 'link.color'],
  },
  'color.primary.hover': {
    value: '#1d4ed8',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.background.hover'],
  },
  'color.primary.active': {
    value: '#1e40af',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.background.active'],
  },
  'color.secondary.base': {
    value: '#64748b',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['text.muted', 'border.default'],
  },
  'color.success.base': {
    value: '#22c55e',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['alert.success.bg', 'icon.success'],
  },
  'color.warning.base': {
    value: '#f59e0b',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['alert.warning.bg'],
  },
  'color.error.base': {
    value: '#ef4444',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['alert.error.bg', 'input.error.border'],
  },
  'color.background.page': {
    value: '#ffffff',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['card.background', 'modal.background'],
  },
  'color.background.subtle': {
    value: '#f8fafc',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['table.row.alt', 'sidebar.background'],
  },
  'color.text.primary': {
    value: '#0f172a',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['heading.color', 'body.color'],
  },
  'color.text.secondary': {
    value: '#475569',
    type: 'color',
    category: 'color',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['label.color', 'caption.color'],
  },

  // Dark theme variants
  'color.primary.base.dark': {
    value: '#3b82f6',
    type: 'color',
    category: 'color',
    theme: 'dark',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.background'],
  },
  'color.background.page.dark': {
    value: '#0f172a',
    type: 'color',
    category: 'color',
    theme: 'dark',
    scale: 'desktop',
    references: [],
    referencedBy: ['card.background'],
  },
  'color.text.primary.dark': {
    value: '#f1f5f9',
    type: 'color',
    category: 'color',
    theme: 'dark',
    scale: 'desktop',
    references: [],
    referencedBy: ['heading.color'],
  },

  // Spacing Tokens
  'spacing.xs': {
    value: '4px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.padding.x', 'icon.margin'],
  },
  'spacing.sm': {
    value: '8px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['input.padding', 'card.gap'],
  },
  'spacing.md': {
    value: '16px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['section.padding', 'modal.padding'],
  },
  'spacing.lg': {
    value: '24px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['container.padding', 'page.margin'],
  },
  'spacing.xl': {
    value: '32px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['hero.padding'],
  },
  'spacing.2xl': {
    value: '48px',
    type: 'dimension',
    category: 'spacing',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['section.gap'],
  },

  // Typography Tokens
  'font.family.sans': {
    value: "'Inter', -apple-system, sans-serif",
    type: 'fontFamily',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['body.fontFamily', 'button.fontFamily'],
  },
  'font.family.mono': {
    value: "'JetBrains Mono', monospace",
    type: 'fontFamily',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['code.fontFamily'],
  },
  'font.size.xs': {
    value: '12px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['caption.fontSize', 'badge.fontSize'],
  },
  'font.size.sm': {
    value: '14px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['body.small.fontSize'],
  },
  'font.size.base': {
    value: '16px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['body.fontSize', 'input.fontSize'],
  },
  'font.size.lg': {
    value: '18px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['h4.fontSize'],
  },
  'font.size.xl': {
    value: '20px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['h3.fontSize'],
  },
  'font.size.2xl': {
    value: '24px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['h2.fontSize'],
  },
  'font.size.3xl': {
    value: '30px',
    type: 'dimension',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['h1.fontSize'],
  },
  'font.weight.normal': {
    value: '400',
    type: 'fontWeight',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['body.fontWeight'],
  },
  'font.weight.medium': {
    value: '500',
    type: 'fontWeight',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.fontWeight'],
  },
  'font.weight.semibold': {
    value: '600',
    type: 'fontWeight',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['heading.fontWeight'],
  },
  'font.weight.bold': {
    value: '700',
    type: 'fontWeight',
    category: 'typography',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['h1.fontWeight'],
  },

  // Border Tokens
  'border.radius.sm': {
    value: '4px',
    type: 'dimension',
    category: 'border',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['input.borderRadius', 'badge.borderRadius'],
  },
  'border.radius.md': {
    value: '6px',
    type: 'dimension',
    category: 'border',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.borderRadius', 'card.borderRadius'],
  },
  'border.radius.lg': {
    value: '8px',
    type: 'dimension',
    category: 'border',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['modal.borderRadius'],
  },
  'border.radius.full': {
    value: '9999px',
    type: 'dimension',
    category: 'border',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['avatar.borderRadius', 'pill.borderRadius'],
  },

  // Shadow Tokens
  'shadow.sm': {
    value: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    type: 'boxShadow',
    category: 'effect',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['input.shadow', 'button.shadow'],
  },
  'shadow.md': {
    value: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
    type: 'boxShadow',
    category: 'effect',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['card.shadow', 'dropdown.shadow'],
  },
  'shadow.lg': {
    value: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
    type: 'boxShadow',
    category: 'effect',
    theme: 'light',
    scale: 'desktop',
    references: [],
    referencedBy: ['modal.shadow'],
  },

  // Animation Tokens
  'animation.duration.fast': {
    value: '150ms',
    type: 'duration',
    category: 'animation',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['button.transition', 'input.transition'],
  },
  'animation.duration.normal': {
    value: '300ms',
    type: 'duration',
    category: 'animation',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['modal.transition', 'dropdown.transition'],
  },
  'animation.easing.default': {
    value: 'cubic-bezier(0.4, 0, 0.2, 1)',
    type: 'cubicBezier',
    category: 'animation',
    theme: 'all',
    scale: 'desktop',
    references: [],
    referencedBy: ['all.transition'],
  },

  // Component Tokens (semantic)
  'button.background': {
    value: '{color.primary.base}',
    type: 'color',
    category: 'component',
    theme: 'light',
    scale: 'desktop',
    references: ['color.primary.base'],
    referencedBy: [],
  },
  'button.borderRadius': {
    value: '{border.radius.md}',
    type: 'dimension',
    category: 'component',
    theme: 'all',
    scale: 'desktop',
    references: ['border.radius.md'],
    referencedBy: [],
  },
  'card.background': {
    value: '{color.background.page}',
    type: 'color',
    category: 'component',
    theme: 'light',
    scale: 'desktop',
    references: ['color.background.page'],
    referencedBy: [],
  },
  'card.shadow': {
    value: '{shadow.md}',
    type: 'boxShadow',
    category: 'component',
    theme: 'light',
    scale: 'desktop',
    references: ['shadow.md'],
    referencedBy: [],
  },
}
